

(let ((define $#UID_5E5:top (let ((define $#UID_5EC:top (make $#UID_6B0 #0 ())))
       (let ((define $#UID_5ED:ptr "(some data type)"))
         (let ((define $#UID_5EE:top (let ((define $#UID_5EF:top (make $#UID_6AF #0 ($#UID_5ED:ptr $#UID_5ED:ptr $#UID_5ED:ptr $#UID_5ED:ptr))))
                (let ((define $#UID_5F0:top (make $#UID_6AE #0 ())))
                  (let ((define $#UID_5F1:ptr "(some data type)"))
                    (let ((define $#UID_5F2:top (let ((define $#UID_5F3:top (make $#UID_6AD #0 ($#UID_5F1:ptr $#UID_5F1:ptr $#UID_5F1:ptr))))
                           (let ((define $#UID_5F4:top (lambda ($#UID_6AA:top)
                                (lambda ($#UID_6AB:top)
                                  (prim ($#UID_6AC:int) ("infixLt(Int, Int): Boolean" $#UID_6AA:int $#UID_6AB:int) 
                                      $#UID_6AC:top)))))
                             (let ((define $#UID_5F5:top (lambda ($#UID_6A7:top)
                                  (lambda ($#UID_6A8:top)
                                    (prim ($#UID_6A9:int) ("infixGt(Int, Int): Boolean" $#UID_6A7:int $#UID_6A8:int) 
                                        $#UID_6A9:top)))))
                               (let ((define $#UID_5F6:top (lambda ($#UID_6A4:top)
                                    (lambda ($#UID_6A5:top)
                                      (prim ($#UID_6A6:int) ("infixAdd(Int, Int): Int" $#UID_6A4:int $#UID_6A5:int) 
                                          $#UID_6A6:top)))))
                                 (let ((define $#UID_5F7:top (lambda ($#UID_6A1:top)
                                      (lambda ($#UID_6A2:top)
                                        (prim ($#UID_6A3:int) ("infixSub(Int, Int): Int" $#UID_6A1:int $#UID_6A2:int) 
                                            $#UID_6A3:top)))))
                                   (let ((define $#UID_5F8:top (make $#UID_6A0 #0 ())))
                                     (let ((define $#UID_5F9:top (lambda ($#UID_69E:top)
                                          (prim ($#UID_69F:int) ("read(String): Int" $#UID_69E:str) 
                                              $#UID_69F:top))))
                                       (let ((define $#UID_5FA:top (lambda ($#UID_69C:top)
                                            (prim ($#UID_69D:top) ("println(String): Unit" $#UID_69C:str) 
                                                $#UID_69D:top))))
                                         (let ((define $#UID_5FB:ptr "(some data type)"))
                                           (let ((define $#UID_5FC:top (let ((define $#UID_5FD:top (make $#UID_69B #0 ($#UID_5FB:ptr $#UID_5FB:ptr $#UID_5FB:ptr))))
                                                  (let ((define $#UID_5FE:ptr "(some forall type)"))
                                                    (let ((define $#UID_5FF:top (let ((define $#UID_600:top (make $#UID_69A #0 ((lambda ($#UID_698:top)
                                                                  (let ((define $#UID_699:top $#UID_5FE:ptr))
                                                                      $#UID_699:top))
                                                                  $#UID_5FE:ptr
                                                                  $#UID_5FE:ptr
                                                                  $#UID_5FE:ptr))))
                                                           (let ((define $#UID_601:ptr "(some data type)"))
                                                             (let ((define $#UID_602:top (let ((define $#UID_603:top (make $#UID_697 #0 ($#UID_601:ptr $#UID_601:ptr $#UID_601:ptr $#UID_601:ptr))))
                                                                    (let ((define $#UID_604:top (lambda ($#UID_672:top)
                                                                         (lambda ($#UID_673:top)
                                                                           (let ((define $#UID_674:top (let ((define $#UID_676:top (let ((define $#UID_694:top (project $#UID_600:top $#UID_696 #0 2)))
                                                                                         (let ((define $#UID_695:top $#UID_694:top))
                                                                                           $#UID_695:top))))
                                                                                    (let ((define $#UID_677:ptr (fresh-label)))
                                                                                      (dhandle Deep $#UID_677:ptr
                                                                                      ((#0 ($#UID_682:(fun Effectful (top) top) $#UID_683:top) (lambda ($#UID_684:top)
                                                                                          (let ((define $#UID_685:top (let ((define $#UID_686:top (let ((define $#UID_687:top (let ((define $#UID_688:top (let ((define $#UID_68A:top (project $#UID_5FD:top $#UID_68B #0 2)))
                                                                                                                  $#UID_68A:top)))
                                                                                                             (make $#UID_689 #0 ()))))
                                                                                                        $#UID_687:top)))
                                                                                                   ($#UID_682:(fun Effectful (top) top) $#UID_686:top))))
                                                                                              ($#UID_685:top $#UID_683:top))))
                                                                                          (#1 ($#UID_68C:(fun Effectful (top) top)
                                                                                          $#UID_68D:top)
                                                                                          (let ((define $#UID_68E:top (let ((define $#UID_692:top (project $#UID_5FD:top $#UID_693 #0 2)))
                                                                                                 $#UID_692:top)))
                                                                                            (match ($#UID_68D:top
                                                                                                $#UID_691)
                                                                                            (#0 () 
                                                                                                  (lambda ($#UID_68F:top)
                                                                                                  (let ((define $#UID_690:top ($#UID_68C:(fun Effectful (top) top) $#UID_68F:top)))
                                                                                                      ($#UID_690:top $#UID_68F:top))))
                                                                                            (_ () 
                                                                                                  (prim () ("non-exhaustive match" ) 
                                                                                                    0)))))
                                                                                      )
                                                                                      (let ((define $#UID_679:top ($#UID_673:top $#UID_677:ptr)))
                                                                                          (let ((define $#UID_67A:top (let ((define $#UID_67B:top (let ((define $#UID_67C:top (let ((define $#UID_67E:top (project $#UID_5FD:top $#UID_67F #0 2)))
                                                                                                           $#UID_67E:top)))
                                                                                                      (make $#UID_67D #0 ()))))
                                                                                                 $#UID_67B:top)))
                                                                                            ($#UID_679:top $#UID_67A:top))))))))
                                                                               (let ((define $#UID_675:top $#UID_674:top))
                                                                                 ($#UID_675:top $#UID_672:top)))))))
                                                                      (let ((define $#UID_605:top (lambda ($#UID_662:top)
                                                                           (let ((define $#UID_663:top $#UID_662:top))
                                                                               (let ((define $#UID_664:top (let ((define $#UID_670:top (project $#UID_603:top $#UID_671 #0 2)))
                                                                                      $#UID_670:top)))
                                                                                 (match ($#UID_663:top
                                                                                     $#UID_66F)
                                                                                 (#0 () 
                                                                                       (let ((define $#UID_665:top (let ((define $#UID_666:top (let ((define $#UID_668:top (project $#UID_603:top $#UID_669 #0 3)))
                                                                                                   $#UID_668:top)))
                                                                                              (make $#UID_667 #1 ()))))
                                                                                         $#UID_665:top))
                                                                                     (#1 () 
                                                                                       (let ((define $#UID_66A:top (let ((define $#UID_66B:top (let ((define $#UID_66D:top (project $#UID_603:top $#UID_66E #0 2)))
                                                                                                   $#UID_66D:top)))
                                                                                              (make $#UID_66C #0 ()))))
                                                                                         $#UID_66A:top))
                                                                                 (_ () 
                                                                                       (prim () ("non-exhaustive match" ) 
                                                                                         0))))))))
                                                                        (let ((define $#UID_606:top (let ((define $#UID_61F:top (let ((define $#UID_658:top (let ((define $#UID_65D:top (let ((define $#UID_65E:top (let ((define $#UID_660:top (project $#UID_603:top $#UID_661 #0 2)))
                                                                                                   $#UID_660:top)))
                                                                                              (make $#UID_65F #0 ()))))
                                                                                         $#UID_65D:top)))
                                                                                    (let ((define $#UID_659:top (let ((define $#UID_65A:top $#UID_604:top))
                                                                                           (let ((define $#UID_65B:top $#UID_65A:top))
                                                                                             (let ((define $#UID_65C:top $#UID_65B:top))
                                                                                               $#UID_65C:top)))))
                                                                                      ($#UID_659:top $#UID_658:top)))))
                                                                               (let ((define $#UID_620:top (lambda ($#UID_621:top)
                                                                                    (lambda ($#UID_622:top)
                                                                                      (let ((define $#UID_623:top (let ((define $#UID_656:top (project $#UID_5FD:top $#UID_657 #0 2)))
                                                                                               $#UID_656:top)))
                                                                                          (match ($#UID_622:top
                                                                                              $#UID_655)
                                                                                          (#0 () 
                                                                                                (let ((define $#UID_624:top (let ((define $#UID_637:top (let ((define $#UID_64B:top (lambda ($#UID_64E:top)
                                                                                                               (lambda ($#UID_64F:top)
                                                                                                                 (let ((define $#UID_650:top (let ((define $#UID_652:top (project $#UID_600:top $#UID_654 #0 2)))
                                                                                                                          (let ((define $#UID_653:top $#UID_652:top))
                                                                                                                            $#UID_653:top))))
                                                                                                                     (dop $#UID_64E:top (#0
                                                                                                                     top
                                                                                                                     $#UID_64F:top) ($#UID_651:top) $#UID_651:top))))))
                                                                                                            (let ((define $#UID_64C:top (let ((define $#UID_64D:top $#UID_64B:top))
                                                                                                                   $#UID_64D:top)))
                                                                                                              ($#UID_64C:top $#UID_621:top)))))
                                                                                                       (let ((define $#UID_638:top (let ((define $#UID_639:top (let ((define $#UID_63A:top (let ((define $#UID_641:top (lambda ($#UID_644:top)
                                                                                                                           (lambda ($#UID_645:top)
                                                                                                                             (let ((define $#UID_646:top (let ((define $#UID_648:top (project $#UID_600:top $#UID_64A #0 3)))
                                                                                                                                      (let ((define $#UID_649:top $#UID_648:top))
                                                                                                                                        $#UID_649:top))))
                                                                                                                                 (dop $#UID_644:top (#1
                                                                                                                                 top
                                                                                                                                 $#UID_645:top) ($#UID_647:top) $#UID_647:top))))))
                                                                                                                        (let ((define $#UID_642:top (let ((define $#UID_643:top $#UID_641:top))
                                                                                                                               $#UID_643:top)))
                                                                                                                          ($#UID_642:top $#UID_621:top)))))
                                                                                                                   (let ((define $#UID_63B:top (let ((define $#UID_63C:top (let ((define $#UID_63D:top (let ((define $#UID_63F:top (project $#UID_5FD:top $#UID_640 #0 2)))
                                                                                                                                    $#UID_63F:top)))
                                                                                                                               (make $#UID_63E #0 ()))))
                                                                                                                          $#UID_63C:top)))
                                                                                                                     ($#UID_63A:top $#UID_63B:top)))))
                                                                                                              ($#UID_605:top $#UID_639:top))))
                                                                                                         ($#UID_637:top $#UID_638:top)))))
                                                                                                  (let ((define $#UID_625:top $#UID_624:top))
                                                                                                    (let ((define $#UID_626:top (let ((define $#UID_62D:top (lambda ($#UID_630:top)
                                                                                                              (lambda ($#UID_631:top)
                                                                                                                (let ((define $#UID_632:top (let ((define $#UID_634:top (project $#UID_600:top $#UID_636 #0 3)))
                                                                                                                         (let ((define $#UID_635:top $#UID_634:top))
                                                                                                                           $#UID_635:top))))
                                                                                                                    (dop $#UID_630:top (#1
                                                                                                                    top
                                                                                                                    $#UID_631:top) ($#UID_633:top) $#UID_633:top))))))
                                                                                                           (let ((define $#UID_62E:top (let ((define $#UID_62F:top $#UID_62D:top))
                                                                                                                  $#UID_62F:top)))
                                                                                                             ($#UID_62E:top $#UID_621:top)))))
                                                                                                      (let ((define $#UID_627:top (let ((define $#UID_628:top (let ((define $#UID_629:top (let ((define $#UID_62B:top (project $#UID_5FD:top $#UID_62C #0 2)))
                                                                                                                       $#UID_62B:top)))
                                                                                                                  (make $#UID_62A #0 ()))))
                                                                                                             $#UID_628:top)))
                                                                                                        ($#UID_626:top $#UID_627:top))))))
                                                                                          (_ () 
                                                                                                (prim () ("non-exhaustive match" ) 
                                                                                                  0))))))))
                                                                                 ($#UID_61F:top $#UID_620:top)))))
                                                                          (let ((define $#UID_607:top $#UID_606:top))
                                                                            (let ((define $#UID_608:top (lambda ($#UID_619:top)
                                                                                 (let ((define $#UID_61A:top $#UID_619:top))
                                                                                     (let ((define $#UID_61B:top (let ((define $#UID_61D:top (project $#UID_603:top $#UID_61E #0 2)))
                                                                                            $#UID_61D:top)))
                                                                                       (match ($#UID_61A:top
                                                                                           $#UID_61C)
                                                                                       (#0 () 
                                                                                             "True")
                                                                                           (#1 () 
                                                                                             "False")
                                                                                       (_ () 
                                                                                             (prim () ("non-exhaustive match" ) 
                                                                                               0))))))))
                                                                              (let ((define $#UID_609:top (let ((define $#UID_618:top ($#UID_608:top $#UID_607:top)))
                                                                                     ($#UID_5FA:top $#UID_618:top))))
                                                                                (let ((define $#UID_60A:top $#UID_609:top))
                                                                                  (let ((define $#UID_60B:top (project $#UID_5F3:top $#UID_617 #0 2)))
                                                                                    (let ((define $#UID_60C:top (project $#UID_5FD:top $#UID_616 #0 2)))
                                                                                      (let ((define $#UID_60D:top (project $#UID_600:top $#UID_615 #0 2)))
                                                                                        (let ((define $#UID_60E:top (project $#UID_600:top $#UID_614 #0 3)))
                                                                                          (let ((define $#UID_60F:top (project $#UID_603:top $#UID_613 #0 2)))
                                                                                            (let ((define $#UID_610:top (project $#UID_603:top $#UID_612 #0 3)))
                                                                                              (make $#UID_611 #0 ($#UID_5EC:top $#UID_5F0:top $#UID_60B:top $#UID_5F4:top $#UID_5F5:top $#UID_5F6:top $#UID_5F7:top $#UID_5F8:top $#UID_5F9:top $#UID_5FA:top $#UID_5FD:top $#UID_60C:top $#UID_600:top $#UID_60D:top $#UID_60E:top $#UID_603:top $#UID_60F:top $#UID_610:top $#UID_604:top $#UID_605:top $#UID_607:top $#UID_608:top))))))))))))))))))
                                                               $#UID_602:top)))))
                                                      $#UID_5FF:top)))))
                                             $#UID_5FC:top))))))))))))
                      $#UID_5F2:top))))))
           $#UID_5EE:top)))))
  (let ((define $#UID_5E6:top $#UID_5E5:top))
    (let ((define $#UID_5E7:top $#UID_5E6:top))
      (let ((define $#UID_5E8:top $#UID_5E7:top))
        (let ((define $#UID_5E9:top $#UID_5E8:top))
          (let ((define $#UID_5EA:top $#UID_5E9:top))
            (make $#UID_5EB #0 ())))))))