(define $count:top (lambda ($n:int)
  (letrec ((define $loop:top (lambda ($n:int) 
     (if0 $n:int 0
       (op $eff ($n:int) ($n1:int)
         ($loop:top $n1:int)
       )
     )
   )))
   (handle Deep $eff (($a:int $resume:top) 
       (prim ($a1:int) ("infixSub(Int, Int): Int" $a:int 1)
          ($resume:top $a1:int)
       )
     )
     ($loop:top $n:int))
  )
))

($count:top 10)
